/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        './resources/**/*.blade.php',
        './resources/**/*.js',
    ],
    theme: {
        extend: {
            colors: {
                'inverse-surface': '#2e3132',
                'outline-variant': '#c5c6ce',
                'surface-container-high': '#e7e8e9',
                'surface-variant': '#e1e3e4',
                'primary-fixed-dim': '#b6c7e9',
                'tertiary-container': '#0c1f26',
                tertiary: '#000304',
                'on-surface-variant': '#44474d',
                'tertiary-fixed-dim': '#b6cad2',
                outline: '#75777e',
                'on-tertiary': '#ffffff',
                'surface-tint': '#4e5f7c',
                'secondary-fixed-dim': '#e9c176',
                'on-primary-fixed': '#081c36',
                'on-primary': '#ffffff',
                'on-secondary': '#ffffff',
                'on-tertiary-fixed-variant': '#374951',
                'surface-container-highest': '#e1e3e4',
                'on-tertiary-container': '#758890',
                'on-error': '#ffffff',
                'on-tertiary-fixed': '#0b1e24',
                'on-primary-container': '#7586a5',
                'surface-container-lowest': '#ffffff',
                'secondary-container': '#fed488',
                surface: '#f8f9fa',
                'error-container': '#ffdad6',
                error: '#ba1a1a',
                'tertiary-fixed': '#d2e6ef',
                'on-secondary-container': '#785a1a',
                'primary-fixed': '#d6e3ff',
                'secondary-fixed': '#ffdea5',
                'on-background': '#191c1d',
                secondary: '#775a19',
                'on-error-container': '#93000a',
                'surface-bright': '#f8f9fa',
                'primary-container': '#0a1d37',
                background: '#f8f9fa',
                'inverse-on-surface': '#f0f1f2',
                'on-surface': '#191c1d',
                primary: '#00030a',
                'on-secondary-fixed': '#261900',
                'on-secondary-fixed-variant': '#5d4201',
                'surface-dim': '#d9dadb',
                'inverse-primary': '#b6c7e9',
                'surface-container': '#edeeef',
                'surface-container-low': '#f3f4f5',
            },
            borderRadius: {
                DEFAULT: '0.125rem',
                lg: '0.25rem',
                xl: '0.5rem',
                full: '0.75rem',
            },
            spacing: {
                gutter: '24px',
                'stack-md': '16px',
                'margin-edge': '32px',
                'stack-sm': '8px',
                unit: '8px',
                'container-max': '1280px',
                'stack-lg': '32px',
            },
            fontFamily: {
                'body-md': ['Inter'],
                'label-sm': ['Inter'],
                'label-md': ['Inter'],
                'headline-md': ['Inter'],
                'headline-xl': ['Inter'],
                'body-lg': ['Inter'],
                'headline-lg': ['Inter'],
                inter: ['Inter', 'sans-serif'],
            },
            fontSize: {
                'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
                'label-sm': ['12px', { lineHeight: '1.2', fontWeight: '600' }],
                'label-md': ['14px', { lineHeight: '1.2', letterSpacing: '0.01em', fontWeight: '500' }],
                'headline-md': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
                'headline-xl': ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
                'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
                'headline-lg': ['32px', { lineHeight: '1.3', fontWeight: '600' }],
            },
            maxWidth: {
                'container-max': '1280px',
            },
        },
    },
    plugins: [
        require('@tailwindcss/forms'),
        require('@tailwindcss/container-queries'),
    ],
};
